### ISSUE TITLE
Outsource / Automate Cache-Building from Wiiflow

### ISSUE THREAD

**Issue by kaisersozeh** [einsteinx2/wiiflow-lite-einstein-mod#5]
The images actually used by wiiflow are a cache of the png's found in the 'covers folders. It's wiiflow that build's this cache of images, with large collections taking many hours to complete the process, manually moving focus from one image to the next.
It's intended that the cache is built on-the-fly, as users explore new content, but performance is severely impeded by the caching process, leading to a frustrating user experience.
Automate the in-wiiflow cache building process to an executable batch, initialised from within the interface, such that leavers can leave wiiflow running the process unsupervised.
Generate command line software to build the cache using windows, mac, linux
Generate GUI software to achieve this.

**Comment by einsteinx2** [comment]
This can definitely be done. Since we have the code that runs when an individual game is selected, it should be as easy as going through all the games and running that code. Since we already have a similar example with the cover downloader, it should be possible to copy that and modify it for this purpose.

**Comment by einsteinx2** [comment]
Looks like Wiimpathy already did this and Fledge is merging it into WiiFlow Lite!
